version: '2.12.2'
services:
     php-apache:
      image : php:apache
      # environnement:
      #  - USER_NAME=Lorine
      #  - USER_PASSWORD=LOLO12
      volumes:
       - ./index.php:/var/www/html
      depends_on:
       - api-pozos
      ports: 
       - 8002:8069


     api-pozos:
      image : api-pozos:0.1
      volumes:
       - type: bind
         source: api/student_age.json
         target: /data/student_age.json
      ports: 
       - 4000:5000 

