version: '2.12.2'
services:
     Site_Web:
      build: .
      image : php:apache
      restart: always
      environment:
       USER_NAME: Lorine
       USER_PASSWORD: LOLO12
      volumes:
       - ./website:/var/www/html
      depends_on:
       - API
      ports: 
       - 8002:8069


     API:
      image : api-pozos:0.1
      restart: always
      volumes:
       - type: bind
         source: api/student_age.json
         target: /data/student_age.json
      ports: 
       - 4000:5000 

